### ISSUE TITLE
 openjdk:7-jdk-alpine does not work happy with TZ env

### ISSUE THREAD

**Issue by likunbyl** [docker-library/openjdk#123]
I'm running a container based on a image that build from  openjdk:7-jdk-alpine, and setup TZ=GMT+8, which should be +8 hours from GMT time, but actually it's -8 hours from GMT time.  like the following:

bash-4.3# export TZ=CST
bash-4.3# date
Sat Jun 24 14:20:33 CST 2017
bash-4.3# export TZ=GMT+8
bash-4.3# date
Sat Jun 24 06:20:42 GMT 2017
bash-4.3# export TZ=GMT-8
bash-4.3# date
Sat Jun 24 22:20:50 GMT 2017

something wrong？

likun

**Comment by tianon** [comment]
The `date` binary that you're running has nothing to do with OpenJDK, and is instead provided by the underlying Alpine distribution.  I believe `date` in Alpine is provided by Busybox, so I'd recommend trying somewhere with one of those two upstreams for more help digging into where this problem lies and how to get it fixed.
