### ISSUE TITLE
Recent update in Java 8 images from Jessie to Stretch has breaking changes.

### ISSUE THREAD

**Issue by annaspyker** [docker-library/openjdk#125]
The [commit](https://github.com/docker-library/openjdk/commit/ae4562dcd2d99eb9d6224517f9e6b4ab4c2b4672#diff-e6f73dfdd5804567c5ec8854bad37e51) from four days ago has changed the base debian image from buildpack-deps:jessie-curl to buildpack-deps:stretch-curl. It seems that the majority of the OpenJDK Java 8 images were impacted by this commit.

The stretch release does not include the libatlas3gf-base package, whereas the jessie release did (https://packages.debian.org/search?keywords=libatlas3gf&searchon=names&suite=oldstable&section=all). This has broken my build. 

I would like to revert back to the older version of openjdk:8, but it appears this has been overwritten with the new version. This gives me little confidence that your docker image releases will be stable. For now I have had to move to a different Java 8 base image due to not being able to use an older version of your image.

**Comment by ReeceRobinson** [comment]
It seems an odd decision to replace a version with another build so when things break (as they can do with new builds) there is no way for the consumer of that artefact to revert?

**Comment by yosifkit** [comment]
When we evaluated the decision, we decided it was either update the base image or not have any more java updates.  But, we do keep a recorded history of every image by their full sha256 digest in https://github.com/docker-library/repo-info/, so you can find past openjdk 8 images in https://github.com/docker-library/repo-info/blob/master/repos/openjdk/remote/8.md (just look at the git history to find the old sha 256 digests that referred to openjdk 8).

It looks like `libatlas3gf-base` is a transitional package for `libatlas3-base`, so you should try installing that instead.

**Comment by annaspyker** [comment]
Thanks for the prompt reply. As a fix I will change my base image to the versioned image you linked above.

**Comment by rstrauss** [comment]
I don't understand @yosifkit (I'm new to all this).  You say to find past images at: https://github.com/docker-library/repo-info/blob/master/repos/openjdk/remote/8.md

I'm looking for the May 15th release mentioned on this page:  https://github.com/docker-library/openjdk/commits/ae4562dcd2d99eb9d6224517f9e6b4ab4c2b4672/8-jre/Dockerfile
I see the commit SHA, but not a sha256 for the release..

There's no May 15th release on the page you give.  And what does its `3723419e5e6ce64ad9f5c7c4bfe9c6441540cd58dab37a33880c14cb4f5e3586` refer to?  Is that the latest, or a previous one?

**Comment by yosifkit** [comment]
The `372341...` number is the sha256 digest of the image (which is the newest image that was tagged as `openjdk:8`). The digest is generated by docker on `push` of the image. So the current `openjdk:8` images can be pulled via:
```console
$ docker pull openjdk@sha256:3723419e5e6ce64ad9f5c7c4bfe9c6441540cd58dab37a33880c14cb4f5e3586
sha256:3723419e5e6ce64ad9f5c7c4bfe9c6441540cd58dab37a33880c14cb4f5e3586: Pulling from library/openjdk
c75480ad9aaf: Pull complete 
18d67befbc4e: Pull complete 
1f5d2d0853c7: Pull complete 
5de358416a75: Pull complete 
4049b231edea: Pull complete 
6617c62c7c10: Pull complete 
aa26fbcddb08: Pull complete 
d5b28339f9cb: Pull complete 
8d7b25fab67a: Pull complete 
Digest: sha256:3723419e5e6ce64ad9f5c7c4bfe9c6441540cd58dab37a33880c14cb4f5e3586
Status: Downloaded newer image for openjdk@sha256:3723419e5e6ce64ad9f5c7c4bfe9c6441540cd58dab37a33880c14cb4f5e3586
$ # which is currently the same value that is printed when you pull the openjdk:8 image
$ docker pull openjdk:8
8: Pulling from library/openjdk
Digest: sha256:3723419e5e6ce64ad9f5c7c4bfe9c6441540cd58dab37a33880c14cb4f5e3586
Status: Downloaded newer image for openjdk:8
```

The [history of the `8.md`](https://github.com/docker-library/repo-info/commits/master/repos/openjdk/remote/8.md) file contains every time a new image was pushed to the Docker Hub that was called `openjdk:8`.  It is not directly tied to commits to here or in docker-library/official-images, since a base image change to `debian` would cause a rebuild of dependent images like `openjdk`.  It is mostly based on periodic pulling of images from the Docker Hub to see when new ones are available and then extracting useful information from the image and Docker Hub.

In the history, you'll find a commit (https://github.com/docker-library/repo-info/commit/e505b460e08645b60425cf5af2c5e309e3eecef0) on May 16th which shows that the sha256 digest of the `openjdk:8` image at that time [changed](https://github.com/docker-library/repo-info/commit/e505b460e08645b60425cf5af2c5e309e3eecef0#diff-6c453ce440edb59482d02b5d35080400R4). You can also see that it corresponds to the openjdk version bump from [`8u121`](https://github.com/docker-library/repo-info/commit/e505b460e08645b60425cf5af2c5e309e3eecef0#diff-6c453ce440edb59482d02b5d35080400L41) to [`8u131`](https://github.com/docker-library/repo-info/commit/e505b460e08645b60425cf5af2c5e309e3eecef0#diff-6c453ce440edb59482d02b5d35080400R41).
