### ISSUE TITLE
openjdk:8-jre not built since December 12th 2017

### ISSUE THREAD

**Issue by albuch** [docker-library/openjdk#161]
It seems the last time the image `openjdk:8-jre` was build is 
```
        "Created": "2017-12-12T15:17:36.669292428Z",
```
(result of `docker pull openjdk:8-jre && docker images inspect openjdk:8-jre`)
And therefor no Debian security fixes were pulled in. Is there something wrong with the automatic build on base image/upstream changes?

**Comment by albuch** [comment]
Well I just saw that none of the reported CVEs have fixes yet so never mind. 
I was basically referring to this issue (https://github.com/docker-library/buildpack-deps/issues/46#issuecomment-242863442) where a roughly 1 month rebuilt time of base images and dependent images was mentioned.

**Comment by qedrakmar** [comment]
Images with security fixes do get prioritized and built in a timely manner.  The 1 month timeframe mentioned in the other thread is the "even if nothing major comes up, we still rebuild them, anyway" timeframe.  Rest assured that if security fixes come in for a high importance CVE, there will be image rebuilds promptly.  

Since this topic is otherwise explained in the comment you referenced above, I'm going to mark this as a duplicate of https://github.com/docker-library/buildpack-deps/issues/46 and close the issue.
