### ISSUE TITLE
Is Alpine image with OpenJDK 8u161 planned in the next time?

### ISSUE THREAD

**Issue by herfort** [docker-library/openjdk#168]
related to #164 
This issue is closed and I don't find any information about release plan for OpenJDK 8u161.

**Comment by tianon** [comment]
As noted in the linked issue https://github.com/docker-library/openjdk/issues/164#issuecomment-361728279 (and the issue it links to, https://github.com/docker-library/openjdk/issues/150#issuecomment-338713389):

> ... for the alpine based images, we are beholden to updates in Alpine Linux.

An update to OpenJDK 8u161 does not exist in Alpine Edge (https://pkgs.alpinelinux.org/packages?name=openjdk8&branch=edge&arch=x86_64), let alone a released version of Alpine (https://pkgs.alpinelinux.org/packages?name=openjdk8&branch=v3.7&arch=x86_64).

Additionally, their bugtracker does not seem to have a relevant version bump request, so that's probably a good place to start.
