### ISSUE TITLE
Wrong architecture for RaspberryPi 3 B - armel instead of armhf

### ISSUE THREAD

**Issue by z0rb** [docker-library/openjdk#170]
Hi,

I have been building docker containers with docker compose on the RPi 3B. When specifying "openjdk:8-jre" as the image the armel variant is pulled. This variant has a different VM and is running in interpreted mode compared to the "arm32v7/openjdk" image that I would expect being pulled.

The result is a significant performance impact. In my case the initialization of a container running wildfly swarm takes 15-20 minutes. With the correct architecture the container is initialized in 1.5 minutes.

Would this be a bug or a feature?

I would like the containers to be portable, so using the specific "arm32v7/openjdk" image would not be an option.

**Comment by yosifkit** [comment]
It is not the fault of the image, but the fault of Docker on pulling when using the manifest list; it just pulls the first image that matches `architecture` and doesn't use `variant` (like `v7`). See the upstream Docker issue: https://github.com/moby/moby/issues/34875.

For now, the workaround is to pull the specific image you want rather than relying on manifest lists: https://hub.docker.com/r/arm32v7/openjdk/.

Related/duplicate issue https://github.com/docker-library/php/issues/518, https://github.com/docker-library/python/issues/240.

**Comment by z0rb** [comment]
Thank you! I came across that issue and skimmed it but didn't realize that moby IS the actual docker upstream. I've built my [image](https://github.com/z0rb/docker-openjdk-wiringpi) specifically for the architecture and subscribed to the issue for changes.

**Comment by rzr** [comment]
Is there any related open bug/task to pick host's architecture and not first one in list ?

**Comment by tianon** [comment]
That's exactly what https://github.com/moby/moby/issues/34875 is.
