### ISSUE TITLE
Will there ever be a v9 image on a stable debian dist?

### ISSUE THREAD

**Issue by chadxz** [docker-library/openjdk#179]
I'd like to use openjdk v9 but I have reservations about building my app on an "experimental" version of debian. Will there ever be a v9 on stretch? Curious as to the reasoning there.

Thank you for all you do to maintain these images, I'm happily using the v8 slim-stretch version and it works great.

**Comment by yosifkit** [comment]
Closing since 9 no longer exists.

As far as building on a stable release of Debian, in order to get the latest releases of openjdk we have to be based on "unstable" or maybe "testing".  Releases of openjdk for 10 and 11 are not even available in a Debian release, only "testing" (aka Buster) and "unstable" (aka Sid).
