### ISSUE TITLE
No such provider: SunPKCS11-NSS on openjdk8

### ISSUE THREAD

**Issue by ravi-k8** [docker-library/openjdk#188]
I have tried the image **openjdk:8-jdk-alpine** which has NSS configured in java.security by default but still I am getting the below exception in my application logs.

Caused by: java.security.NoSuchProviderException: No such provider: SunPKCS11-NSS
	at javax.crypto.Cipher.getInstance(Cipher.java:593) ~[?:1.8.0_151]

From java.security file  
security.provider.10=sun.security.pkcs11.SunPKCS11 ${java.home}/lib/security/nss.cfg

**Comment by tianon** [comment]
I think this might be related to the fact that Alpine doesn't use NSS by default.

Checking `$JAVA_HOME/jre/lib/security/java.security` inside the image seems to imply that it _should_ be enabled, but perhaps doesn't work because NSS itself isn't installed or configured properly?

```console
$ docker pull openjdk:8-jdk-alpine
8-jdk-alpine: Pulling from library/openjdk
Digest: sha256:e82316151c501a2a0f73b3089da8dc867816470a464fcb191db9f88c2343ad53
Status: Image is up to date for openjdk:8-jdk-alpine

$ docker run -it --rm openjdk:8-jdk-alpine sh -c 'grep ^security.provider $JAVA_HOME/jre/lib/security/java.security'
security.provider.1=sun.security.provider.Sun
security.provider.2=sun.security.rsa.SunRsaSign
security.provider.3=sun.security.ec.SunEC
security.provider.4=com.sun.net.ssl.internal.ssl.Provider
security.provider.5=com.sun.crypto.provider.SunJCE
security.provider.6=sun.security.jgss.SunProvider
security.provider.7=com.sun.security.sasl.Provider
security.provider.8=org.jcp.xml.dsig.internal.dom.XMLDSigRI
security.provider.9=sun.security.smartcardio.SunPCSC
security.provider.10=sun.security.pkcs11.SunPKCS11 ${java.home}/lib/security/nss.cfg

$ docker run -it --rm openjdk:8-jdk-alpine sh -c 'cat $JAVA_HOME/jre/lib/security/nss.cfg'
name = NSS
nssLibraryDirectory = /usr/lib
nssDbMode = noDb
attributes = compatibility
handleStartupErrors = ignoreMultipleInitialisation

$ docker run -it --rm openjdk:8-jdk-alpine find /usr/lib -iname '*nss*'
/usr/lib/libnssdbm3.chk
/usr/lib/libnssdbm3.so
/usr/lib/libnssdbm3.so.34
/usr/lib/jvm/java-1.8-openjdk/jre/lib/security/nss.cfg
/usr/lib/libnssckbi.so
/usr/lib/libnssckbi.so.34
/usr/lib/libnss3.so.34
/usr/lib/libnss3.so
/usr/lib/libnssutil3.so
/usr/lib/libnssutil3.so.34
```

So NSS appears to be configured, Java is pointing to it, and has what looks like appropriate configuration.  At this point, the best I can recommend is checking whether there's a open bug in Alpine Linux that's already tracking this, since we install OpenJDK from Alpine as-is and thus any issue here is going to be an upstream one.

Since there's not really anything we can do in the image to fix this pending an investigation with upstream to determine the root cause, I'm going to close.  If there's a fix provided upstream, we'll consume it ASAP (or re-open if it turns out there's something we're doing in the image which has caused this to not work properly).
