### ISSUE TITLE
Why there is no openjdk tag for nanoserver 1709?

### ISSUE THREAD

**Issue by Cherishty** [docker-library/openjdk#203]

**Comment by yosifkit** [comment]
Because it doesn't have powershell and we do not support multi-stage builds in Official Images (see https://github.com/docker-library/official-images/issues/3383).

So we can't `Invoke-WebRequest` to download the ojdk builds, and `Get-FileHash` and `Expand-Archive`.

https://github.com/docker-library/openjdk/blob/59b305bb797b6cb60fa41e74448a68b4f0cdb813/10/jdk/windows/nanoserver-sac2016/Dockerfile
