### ISSUE TITLE
CVE-2017-15400 present in 2.2.1-8+deb9u1

### ISSUE THREAD

**Issue by MMiller-Hairston** [docker-library/openjdk#239]
Could you please update the current images using JAVA_DEBIAN_VERSION 8u181-b13-1~deb9u1 to eliminate the vulnerability. The fix is present in Version 2.2.1-8+deb9u1 according to the CVE.

**Comment by wglambert** [comment]
https://security-tracker.debian.org/tracker/CVE-2017-15400
Looks like cups is fixed in version `2.2.8.5` for sid, which the images for `openjdk:10` and `openjdk:11` are built from
https://github.com/docker-library/openjdk/blob/1c341f869e22b2db077c4f36f9f5d4c407d33c84/11/jdk/slim/Dockerfile#L7
https://github.com/docker-library/openjdk/blob/1c341f869e22b2db077c4f36f9f5d4c407d33c84/11/jdk/Dockerfile#L7

`openjdk:11-jdk-slim`
```console
$ docker run --rm -dit --name openjdk openjdk:11-jdk-slim
$ docker exec -it openjdk bash
root@a9d2df655232:/# dpkg -l | grep cups
ii  libcups2:amd64                2.2.8-5              amd64        Common UNIX Printing System(tm) - Core library
```
`openjdk:11`
```console
$ docker run --rm -dit --name openjdk1 openjdk:11
$ docker exec -it openjdk1 bash
root@9c556096061e:/# dpkg -l | grep cups
ii  libcups2:amd64                2.2.8-5                      amd64        Common UNIX Printing System(tm) - Core library
```
`openjdk:8` uses stretch, the fixed version of cups is then `2.2.1-8+deb9u2`
https://github.com/docker-library/openjdk/blob/1c341f869e22b2db077c4f36f9f5d4c407d33c84/8/jdk/Dockerfile#L7

`openjdk:8-jdk-slim`
```console
$ docker run --rm -dit --name openjdk openjdk:8-jdk-slim
$ docker exec -it openjdk bash
root@eade9295eb82:/# dpkg -l | grep cups
ii  libcups2:amd64               2.2.1-8+deb9u2        amd64        Common UNIX Printing System(tm) - Core library
```

`openjdk:7` uses jessie which isn't affected.
https://github.com/docker-library/openjdk/blob/1c341f869e22b2db077c4f36f9f5d4c407d33c84/7/jdk/Dockerfile#L7

**Comment by MMiller-Hairston** [comment]
@wglambert I apologize, I should have been more specific. I am interested in the openjdk:8-jre-slim which still uses cups version 2.2.1-8+deb9u1.

**Comment by wglambert** [comment]
Try doing a `docker pull`, the image uses `libcups2:amd64  2.2.1-8+deb9u2`

```console
$ docker pull openjdk:8-jre-slim
Unable to find image 'openjdk:8-jre-slim' locally
8-jre-slim: Pulling from library/openjdk
802b00ed6f79: Already exists 
c93b65a61a80: Already exists 
a9885ada077a: Already exists 
a89352ec9377: Already exists 
4afde0273ed2: Pull complete 
f32ac35cfe65: Pull complete 
Digest: sha256:708f68d17be75c2a63518225482649009a5ab23c4edc896440b2ea7e1ac67131
Status: Downloaded newer image for openjdk:8-jre-slim
b0f4a7b81b0effbcb4f00d8a81a3f0006effdf848572c5ce6dd32b6454e06982
```

```console
$ docker run --rm -dit --name openjdk2 openjdk:8-jre-slim
$ docker exec -it openjdk2 bash
root@b0f4a7b81b0e:/# dpkg -l | grep cups
ii  libcups2:amd64               2.2.1-8+deb9u2        amd64        Common UNIX Printing System(tm) - Core library
```

**Comment by MMiller-Hairston** [comment]
That did it. Thank you
