### ISSUE TITLE
docker-library-bot creates wrong commit message

### ISSUE THREAD

**Issue by J0WI** [docker-library/openjdk#246]
For Alpine Linux and Windows at least:
https://github.com/docker-library/openjdk/commit/fdf3bb8d168120655fe39e4098713e704db809df
https://github.com/docker-library/openjdk/commit/47a6539cd18023dafb45db9013455136cc0bca07

**Comment by tianon** [comment]
Bah, that's not great.  I've poured over the script again (https://github.com/docker-library/oi-janky-groovy/blob/bfaa163edf15f3bbc2782e0658b3e2fd025b275a/update.sh/target-pipeline.groovy at the time these would've run) and I can't see where the issue is and we haven't had a similar issue before.  Also the log purging at https://doi-janky.infosiftr.net/job/update.sh/job/openjdk/ is a tad too aggressive for me to go back and look at the logs for the builds that produced these, so I'm really not sure what's happened here.  I think we just need to keep a little bit closer eye on it in case it happens again (and that's the best we can really do here).

**Comment by J0WI** [comment]
@tianon it happened again: https://github.com/docker-library/openjdk/commit/38cb0eb077acf2a429f32a879903cd305733d561

**Comment by tianon** [comment]
Indeed, see https://github.com/docker-library/openjdk/pull/268#issuecomment-453258763
