### ISSUE TITLE
12-ea-jdk based on "slim", not "stretch" like 11-jdk

### ISSUE THREAD

**Issue by ericis** [docker-library/openjdk#265]
Although an "early access" image, the `12-ea-jdk` image does not reflect the existing OS standard that previous jdk versions did (e.g. `11-jdk`, `8-jdk`)

Is this a planned breaking change? (e.g. `apt-get` doesn't exist)

**Example:**
* `11-jdk` is based on [`buildpack-deps:sid-scm`](https://github.com/docker-library/openjdk/blob/6f7c70eb527c39c3f315454b84fe0f776aa019fb/11/jdk/Dockerfile#L7)
* `12-ea-jdk` is based on [`oraclelinux:7-slim`](https://github.com/docker-library/openjdk/blob/6f7c70eb527c39c3f315454b84fe0f776aa019fb/12/jdk/oracle/Dockerfile#L1) which is, in turn, based on `scratch` with Oracle's own OS implementation

**Comment by tianon** [comment]
Yep, entirely intentional.  See https://github.com/docker-library/openjdk/issues/212 and https://github.com/docker-library/openjdk/pull/235 for more details.

We would've made the change for 11 as well if we'd been able to dial those change in before it went GA, but we weren't quite quick enough (and we wanted to make sure the changes were only introduced at a major version, where larger breaking changes are more reasonable/expected).
