### ISSUE TITLE
Image using 13-ea-2-nanoserver-sac2016 throws exception when JMeter reads CSV files

### ISSUE THREAD

**Issue by mixels** [docker-library/openjdk#270]
Ok, I'm seeing an odd behavior when using openjdk:13-ea-2-nanoserver-sac2016 as a base image to containerize Apache JMeter. Here is my Dockerfile:

```
FROM openjdk:13-ea-2-jdk-nanoserver-sac2016
MAINTAINER Richard MacAleese <richard.macaleese@hyland.com>

# When running this image, append additional command line arguments to pass to JMeter to the docker run command.

COPY jmeter jmeter
COPY entrypoint.ps1 .

ENTRYPOINT [ "powershell", "-File", "entrypoint.ps1" ]
```

And here is the Powershell script:

```
cd "C:\jmeter\bin"

.\jmeter -n $args
```

This error occurs when running a JMeter JMX file that reads CSV files for test data.

I post this here because I believe the exception is actually being thrown by awt.dll, which (I'm not Java pro) seems to be a Java native library. I'm not familiar with awt.dll and don't know what its dependencies are. Does this library depend on something like VC++?

**Comment by mixels** [comment]
Apologies for the edit. I was thinking of the time before we discovered that reading CSV files caused this behavior when I initially created this issue.

**Comment by tianon** [comment]
Isn't `awt.dll` an interface to graphics/fonts?  (Those things don't exist in Nano Server, so that's got a high likelihood of being not only related to your troubles but probably causing them.)

From https://docs.oracle.com/javase/7/docs/api/java/awt/package-summary.html:

> Contains all of the classes for creating user interfaces and for painting graphics and images.

**Comment by wglambert** [comment]
Going to close since this variant has been deprecated for a few weeks now https://github.com/docker-library/openjdk/commit/91d42d242a68fa0b8a4cd598c9fac670d4807544

And we don't plan on adding later Nanoserver versions as they don't include Powershell
https://github.com/docker-library/openjdk/issues/295#issuecomment-486407726
>The `nanoserver:sac2016` tag is the only one we were ever based on (the last tag that still contained Powershell and thus was possible for us to build a useful image off of)

For further help you could try asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
