### ISSUE TITLE
Remove src.zip from the latest Java releases

### ISSUE THREAD

**Issue by frol** [docker-library/openjdk#282]
It seems that some of the images do not contain `src.zip` file (namely, Java 8) while others (Java 11+) do have it even in `*-slim` and `*-alpine` tags. The file takes 55MB on disk, which is ~10-20% of the total image size. Can we remove it?

By the way, #251 states that this file is not essential for most of the users.

**Comment by tianon** [comment]
It's entirely an artifact provided (or not provided) by the distribution packages or official release tarballs we consume.  In the former cases, we don't have a lot of control over whether it gets included, and in the latter case, I'm more inclined to keep it so that our image is a faithful representation of those official upstream released artifacts (if it's not something we should be keeping in our image, it should maybe be moved to be a separate artifact from the main binary distribution tarball, or there should be an explicit recommendation to remove it by upstream).

**Comment by frol** [comment]
Would you consider having extra tags (e.g. `stripped`) where the released artifacts gets adapted for general Docker use-case?

My background is based on maintenance of [a popular Docker image of OracleJDK 8](https://github.com/frol/docker-alpine-java) (f.k.a. `frolvlad/alpine-oraclejdk8`) where I successfully [stripped away over 50% (388MB -> 166MB) of the bundle](
https://github.com/frol/docker-alpine-java/blob/master/Dockerfile) while still keeping the functional Java compiler and runtime.

The size difference of the Java 8 and Java 11 tags in this repository is mostly related to the packaging.

**Comment by tianon** [comment]
I'm wary of creating a "stripped" version that doesn't correspond to something upstream explicitly officially publishes or recommends.  The primary reason I'm wary is where do we draw the line?  If we create a "container optimized" variant that strips out things like `src.zip`, what is that saying to folks whose builds actually do require that artifact?  What do we say to the next person who thinks `xyz` bit of the included JDK is not necessary for containers?

**Comment by tianon** [comment]
(In other words, upstream is including all the artifacts they do in their published binary builds for a reason, and it's not really our place to second guess the things that they've chosen to include because they have a _lot_ more context for why those things are included than we do.)

**Comment by frol** [comment]
I see your point. It is unfortunate that Oracle does not provide different bundles or at least an installer within the bundle like they do for Windows:

![](https://i.stack.imgur.com/ZfqsN.png)

(Note, you can disable “source code”)

**Comment by stepanic** [comment]
Hi @tianon I have the similar request as @frol to have an OpenJDK official Docker image with the only runtime (aka JRE since JDK 11) to have size optimized Docker image without `javac` or any other compiling/development tools, just minimal Docker image for executing packaged `.jar` files.

I use https://hub.docker.com/r/frolvlad/alpine-java with tag `jre8-slim` with 46MB instead with 200MB of `openjdk:13-alpine` but it would be more convenient to use officially supported and maintained image by OpenJDK community.

Can you consider to optimise this Dockerfile
https://github.com/docker-library/openjdk/blob/master/13/jdk/alpine/Dockerfile
To keep only required parts of the OpenJDK for runtime, something similar to the legacy Oracle's JRE.

For example, please check this blog post:
https://dzone.com/articles/no-more-jre-packaging-no-big-deal-1

Just with these two steps:
1. Delete the contents of the `jmods/` directory. This eliminates about 74 MB.
2. Delete the `lib/src.zip` to save an additional 45+ MB.
This Docker image can be something similar to the JRE.

**Comment by tianon** [comment]
Honestly, I still strongly recommend using `jlink` to solve this problem -- you'll get a much smaller image than any bog-standard JRE would or even could provide (because it will only explicitly include the exact standard library bits that your application actually needs).

**Comment by stepanic** [comment]
Thank you @tianon, definitely `jlink` is the best solution.

I have followed this tutorial:
https://medium.com/azulsystems/using-jlink-to-build-java-runtimes-for-non-modular-applications-9568c5e70ef4 

But it is simple to achive it with just 2 commands:
https://stackoverflow.com/a/56807371

1. original OpenJDK 13-e1+27 for MacOS has `317MB`
https://download.java.net/java/early_access/jdk13/27/GPL/openjdk-13-ea+27_osx-x64_bin.tar.gz

2. "hacked JRE" with removed `./jmods/*` and `./lib/src.zip` is reduced to `180MB`

3. most optimal solution is to get custom runtime with `jlink`
```
export JAVA_MODULES=java.base,java.compiler,java.datatransfer,java.desktop,java.instrument,java.logging,java.management,java.management.rmi,java.naming,java.net.http,java.prefs,java.rmi,java.scripting,java.se,java.security.jgss,java.security.sasl,java.smartcardio,java.sql,java.sql.rowset,java.transaction.xa,java.xml,java.xml.crypto,jdk.accessibility,jdk.aot,jdk.attach,jdk.charsets,jdk.compiler,jdk.crypto.cryptoki,jdk.crypto.ec,jdk.dynalink,jdk.editpad,jdk.hotspot.agent,jdk.httpserver,jdk.internal.ed,jdk.internal.jvmstat,jdk.internal.le,jdk.internal.opt,jdk.internal.vm.ci,jdk.internal.vm.compiler,jdk.internal.vm.compiler.management,jdk.jartool,jdk.javadoc,jdk.jcmd,jdk.jconsole,jdk.jdeps,jdk.jdi,jdk.jdwp.agent,jdk.jfr,jdk.jlink,jdk.jshell,jdk.jsobject,jdk.jstatd,jdk.localedata,jdk.management,jdk.management.agent,jdk.management.jfr,jdk.naming.dns,jdk.naming.rmi,jdk.net,jdk.pack,jdk.rmic,jdk.scripting.nashorn,jdk.scripting.nashorn.shell,jdk.sctp,jdk.security.auth,jdk.security.jgss,jdk.unsupported,jdk.unsupported.desktop,jdk.xml.dom,jdk.zipfs; /Library/Java/JavaVirtualMachines/jdk-13.jdk/Contents/Home/bin/jlink --no-header-files --no-man-pages --compress=2 --add-modules $JAVA_MODULES --output java-runtime
```
Which is just `91MB` :D


Now I will try to create custom Dockerfile with custom runtime and try to run the application on this custom runtime. 
@tianon thanks again :D

**Comment by stepanic** [comment]
Thank you both, @frol and @tianon for the feedback.
I have created custom Java runtime (reduced OpenJDK) with `jlink`
You can check it here:
https://hub.docker.com/r/microblink/java
