### ISSUE TITLE
JAVA8 Alpine JRE and JDK image tags are broken since last update

### ISSUE THREAD

**Issue by sachingharge** [docker-library/openjdk#285]
Hi Team,

We are seeing below errors for JAVA8 Alpine JRE and JDK image tags.
 /bin/sh: /app/start.sh: not found

Can you please look into this?
We have also noticed that **jre-alpine** tag is no more supported but still exist. Is there any plan to stop supporting this tag in future and should use version specific tags only like **8-jre-alpine**

**Comment by wglambert** [comment]
Are you referring to the [`java` image tags](https://hub.docker.com/_/java?tab=tags), or the [`OpenJDK` tags](https://hub.docker.com/_/openjdk/?tab=tags)

**Comment by sachingharge** [comment]
I am referring to OpenJDK tags.

**Comment by wglambert** [comment]
This might help with seeing the layout of `OpenJDK` and what is supported https://github.com/docker-library/openjdk/issues/272

OpenJDK 11 doesn't have Alpine support https://github.com/docker-library/openjdk/issues/212#issuecomment-424453577 
OpenJDK 12 dropped Alpine support https://github.com/docker-library/openjdk/pull/281
OpenJDK 13 does support Alpine http://jdk.java.net/13/
```console
$ docker pull openjdk:13-alpine
13-alpine: Pulling from library/openjdk
Digest: sha256:3a99d04ea2b4114b57e710cab2560ed86d0629b241a77dea60f0df57704818d8
Status: Downloaded newer image for openjdk:13-alpine
```

Since OpenJDK 11+ is from Oracle; there aren't JRE versions, just JDK. But for 11 we still have the JRE variant which isn't from Oracle

As for your specific error `/bin/sh: /app/start.sh: not found` can you give all the commands you ran and any relevant contextual information or files for reproducing that

**Comment by sachingharge** [comment]
Here is the example Dockerfile for reference where we are getting error "/bin/sh: /app/start.sh: not found"
`FROM openjdk:8-jre-alpine

ADD build/libs /app
ADD docker-bin /app

RUN chown -R daemon:daemon /app && \
    chmod -R 0777 /app && \
    chmod 0500 /app/start.sh

EXPOSE 8080
WORKDIR /app
USER daemon

CMD /app/start.sh`

**Comment by tianon** [comment]
If the shebang of your "start.sh" script is bash, that's a common cause of
that error (the Alpine images don't include Bash).

**Comment by wglambert** [comment]
Closing since this doesn't seem to be an issue with the image

If you have further questions you could try asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability

**Comment by sachingharge** [comment]
> If the shebang of your "start.sh" script is bash, that's a common cause of that error (the Alpine images don't include Bash).

Thanks for your reply and indeed start.sh script has bash.

**Comment by sachingharge** [comment]
Another question, does 8-jre-alpine docker tag is deprecated for **openjdk:jre-alpine**?
