### ISSUE TITLE
Is the JAVA_VERSION env var used

### ISSUE THREAD

**Issue by helgi** [docker-library/openjdk#306]
I have been looking at the various images and noticed that `JAVA_VERSION` is set but never used; is any part of the java toolchain depending that env var?

Many of the images, such as the Debian ones, set `JAVA_DEBIAN_VERSION` and the Alpine ones hardcode the URLs

It seems it originally got created at https://github.com/docker-library/openjdk/blob/3c81719c6288bebc70e7dbf8842af5b7d3616fcf/8/Dockerfile 

Keeping `JAVA_VERSION` seems fine but wanted to see if there was any use for it that I was missing or if this was simply a relic of the past that was never factored out?

**Comment by tianon** [comment]
It's used in `generate-stackbrew-library.sh` to get a consistent display of the version number (so that all the version number munging logic can live in `update.sh` and in the `Dockerfile` itself):

https://github.com/docker-library/openjdk/blob/d617d7e4b951735c512f3d5ac7672f7394115c91/generate-stackbrew-library.sh#L150

**Comment by wglambert** [comment]
Going to close since this seems sufficiently answered
