### ISSUE TITLE
Where is OpenJDK 12 JRE version image?

### ISSUE THREAD

**Issue by XhstormR** [docker-library/openjdk#319]
OpenJDK 12 image on Docker Hub only has JDK version, is there a plan for the JRE version?

**Comment by tianon** [comment]
Our builds for OpenJDK 12 come from https://jdk.java.net/12/, and as you can see they're JDK only.  I don't believe they publish an associated JRE artifact, nor am I aware of any official documentation on what to do with that JDK artifact to turn it into a generic JRE.

What I would recommend though, is that you use a multi-stage build and the `jlink` utility to create for yourself a minimal JRE that only includes the specific standard library classes your application requires (so that you essentially end up creating your own hyper-optimized JRE image). :+1:

For further assistance, I'd recommend trying [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
