### ISSUE TITLE
Base image for openjdk:8

### ISSUE THREAD

**Issue by allamand** [docker-library/openjdk#344]
Hi,

The base Image used for the openjdk is `buildpack-deps:stretch-curl`

It seams that you have redeploy this image we used : ` amd64/openjdk:8u212-jre-slim`and tha base image may have changed since it is not more possible to install the library `libjemalloc1`on debian buster : https://packages.debian.org/buster/libjemalloc1

Can you confirm that the base image changes the debian version ?

How may I prevent to have such regression in futur ? uses the sha of the image instead of it's name ?

Thanks for your inputs

**Comment by tianon** [comment]
I would definitely recommend doing some risk analysis and determining the level to which you're willing to accept image updates -- if that level is zero or near zero, content addressable digests (sha) are the solution you're looking for (`openjdk:8u212-jre-slim@sha256:8d0d4a2ccee06bb6dc9b98e09a5685b3f5126966e895fb835057e23bfb48e982`, for example).  Another option is to pull, re-tag, and re-push to your own namespace or registry in order to control base image updates and force manual review.

If you're willing to accept some change, using the distro-version tags might be an option (`FROM openjdk:8u212-jre-slim-stretch`).

**Comment by tianon** [comment]
Also worth noting is that `libjemalloc` is not gone in Buster, it is merely renamed (likely due to an ABI bump): https://packages.debian.org/buster/libjemalloc2
