### ISSUE TITLE
Can't install libboost-thread1.62.0 into latest openjdk:8-jre-slim

### ISSUE THREAD

**Issue by robooo** [docker-library/openjdk#346]
Before I was using version (bafe4a0f3a02, 5months old) and this line passed without any issue:

```docker
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libboost-thread1.62.0 \
```
I've end up with this error
```
Unable to locate package libboost-thread1.62.0
E: Couldn't find any package by glob 'libboost-thread1.62.0'
E: Couldn't find any package by regex 'libboost-thread1.62.0'
```
How could I fix this? or has the version bafe4a0f3a02 some specific tag which I can use? 
(I can't find it in dockerhub)

**Comment by wglambert** [comment]
The current stable version of that package is [1.67](https://packages.debian.org/buster/libboost-thread1.67.0) if you wanted an older version you'll want to add the Stretch repo

If you have further questions you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability
