### ISSUE TITLE
Join lines and save layers

### ISSUE THREAD

**Issue by hilhorst** [docker-library/openjdk#35]
According to [best practices](https://docs.docker.com/articles/dockerfile_best-practices/) you should [minimize the number of layers](https://docs.docker.com/articles/dockerfile_best-practices/#minimize-the-number-of-layers) if this doesn't impact readability, which I think can be done by combining multiple `ENV` lines in one multiline statement, for instance like this for the 8-jre version:
```
ENV LANG=C.UTF-8 \
	JAVA_VERSION=8u45 \
	JAVA_DEBIAN_VERSION=8u45-b14-1
```
This saves two layers. Three if you push in the `CA_CERTIFICATES_JAVA_VERSION` line too, which I think actually wouldn't be a good thing, in terms of readability.

And I don't know whether unzip is actually needed. If not, it's a best practice to [avoid installing unnecessary packages](https://docs.docker.com/articles/dockerfile_best-practices/#avoid-installing-unnecessary-packages).  If it *is* necessary, you can add it to the same line as where you install the jre package (actually to the same `apt-get install` statement) saving another layer in the image and possibly a tiny bit of time in the build.

**Comment by md5** [comment]
Looks like `unzip` was added in #3. I agree that it's not necessary, but it's possible that removing it would break some existing users. If it's not a particularly large package, it may be best to just leave it.

**Comment by tianon** [comment]
The justification for `unzip` was in the spirit of `buildpack-deps` -- all the tools most people need to get off the ground running with nothing but the base image included by default.  Since the `jre` image doesn't have `javac`, you're more likely going to be grabbing pre-built artifacts like `jar` files, so I'd still hold that both `curl` and `unzip` are useful to have by default IMO.  Looking at `docker history java`, the line that installs `unzip` does only amount to 786.4 kB. :+1:

As for why it's on a separate line, that's actually so we can try to get some overlapping cache from different tags of the image.

The `ENV` lines could be combined, but it would make the `update.sh` script that automates their replacement more complicated, so I'm open to it, but only if the script changes are minimal :+1: (since I'm concerned about maintainability as much as usability -- the most usable image in the world will be pointless if we can't keep it up-to-date effectively :smile:).

**Comment by md5** [comment]
> The justification for unzip was in the spirit of buildpack-deps -- all the tools most people need to get off the ground running with nothing but the base image included by default. Since the jre image doesn't have javac, you're more likely going to be grabbing pre-built artifacts like jar files, so I'd still hold that both curl and unzip are useful to have by default IMO. Looking at docker history java, the line that installs unzip does only amount to 786.4 kB. :+1:

I forgot that the `*-jre` variants don't have `jar` in them, so having `unzip` makes sense at less than 800k.

**Comment by hilhorst** [comment]
I was missing the context of the `update.sh` script. It all makes much more sense now :smile:. I'm really impressed by the code with which you determine the debian version. Very crafty indeed :+1:. That said, I think the fix for the combined `ENV` lines should be pretty simple. I'm at work now, but I'll send you a pull request later today (after I had time to test it on my docker box at home :wink:)

**Comment by hilhorst** [comment]
@tianon, I think I succeeded in keeping the script changes minimal. I hope you agree :smile:.

About having `unzip` on a separate line, what would be the benefit of the cache overlap; saving time or space? For such a small package, wouldn't the bulk of the time go into the `apt-get update` and `rm -rf /var/lib/apt/lists/*`? At the moment you're doing both of those twice.

And you yourself argued that the space for the package is minimal. Wouldn't following the best practice of reducing the number of layers trump this small saving of space?

Sincerely interested in your thoughts on this.

**Comment by md5** [comment]
@hilhorst It can't be build cache overlap since each of the 6 variant images have a different `FROM buildpack-deps:*` (e.g. `java:6-jdk` has `wheezy-scm` while `6-jre` has `wheezy-curl`, and 6, 7, and 8 use `wheezy`, `jessie`, and `sid` respectively).

**Comment by hilhorst** [comment]
@md5 It would cache earlier builds for the same variant, though. In which case we might be getting an older version of the `unzip` package than anticipated;  because we don't specify a version for the `unzip`package, we'd expect to get the latest version, but instead the `RUN` commands still match and we get the same version as when the image was built for the first time, because that is what was cached. 

Come to think of it, how does caching work for the `FROM` line? Because it's built on Docker Hub, I assume we'd be using the latest cached version of the build for that image. So, if that image changes, we'd get the latest version on the next build, but wouldn't the build cache be invalidated from that point on? And would this be different for local builds?

That said, I think it might be an even better idea to add the `unzip` package to the same `apt-get install` statement as where we install `openjdk`. Not just for saving a layer, but also for getting the latest version of the package. I hope this makes sense :smile:.

**Comment by md5** [comment]
@hilhorst The official images are built on their own server, not on Docker Hub itself. [The build scripts](https://github.com/docker-library/official-images/tree/master/bashbrew) are written to rebuild dependent images as necessary. My understanding is that a single build box is being used for the images (in addition to @tianon and @yosifkit's local builds), so the cache on that server persists over time.

As for the `unzip` package, what you're saying about not picking up a new version makes sense in the abstract, but moving it into the same `apt-get` line as the JRE/JDK itself won't fix that definitively without also specifying an `unzip` version. Doing that wouldn't make a ton of sense since there a bunch of unlisted dependencies of the `openjdk-*` packages that are not having their specific versions called out.

I think if there were a problem with the `unzip` package that resulted in a new version being released (say a CVE or DSA), I'm assuming that the base `debian` images would be rebuilt. This was recently done for a `curl` vulnerability I believe. See https://github.com/docker-library/buildpack-deps/issues/24, where the vulnerability is mentioned, though I think it was closed by https://github.com/docker-library/official-images/pull/696, which doesn't mention it.
