### ISSUE TITLE
Base image openkdk:14-jdk-alpine3.10 conatins critical vulnerability for Oniguruma package

### ISSUE THREAD

**Issue by NamrataKokate** [docker-library/openjdk#361]
Hi,

The image openkdk:14-jdk-alpine3.10 conatins the vulneravility (CVE-2019-13224, CVE-2019-13225, CVE-2019-16163) for Oniguruma package. which has been removed in Oniguruma version 6.9.3 (https://github.com/kkos/oniguruma).

Please update the image to remove this vulnerability and ssl and musl 1.1.22-r3 (CVE-2019-1469, CVE-2019-1549, CVE-2019-1563, CVE-2019-1547).

**Comment by wglambert** [comment]
I don't see `Oniguruma` in the image

The image was last updated 4 days ago, upstream's last update was 5 days ago
https://jdk.java.net/14/release-notes

**Comment by yosifkit** [comment]
For CVE-2019-14697, see https://github.com/alpinelinux/docker-alpine/issues/34
For CVE-2019-1563,CVE-2019-1549,CVE-2019-1547, see https://github.com/alpinelinux/docker-alpine/issues/39

Since these are from the Alpine base image we will await their update.  See also https://github.com/docker-library/faq/#why-does-my-security-scanner-show-that-an-image-has-cves
