### ISSUE TITLE
Vulnerability in buster base image

### ISSUE THREAD

**Issue by bharathmuraleedharan** [docker-library/openjdk#383]
AWS ECR scan revealed vulnerability in debian:buster-slim images
![image](https://user-images.githubusercontent.com/3264369/71923486-173ed480-315b-11ea-8351-38b6aa81c20d.png)
https://security-tracker.debian.org/tracker/CVE-2019-18224. Can you please look into it?

**Comment by yosifkit** [comment]
As you can see on the Debian security tracker page, the `libidn2` package is still vulnerable in Buster, so there is nothing we can do to fix it until it shows up in Buster's packages.

It seems unlikely that they are going to backport the fix since it was fixed in Bullseye back in October, but you can try filing a bug or adding to the current bug listed on the tracker page.

See also https://github.com/docker-library/faq/#why-does-my-security-scanner-show-that-an-image-has-cves

**Comment by wglambert** [comment]
Closing since there's nothing actionable for us to do

**Comment by dc0d** [comment]
Currently, the AWS ECR scanner shows two critical vulnerability issues. [One of them](https://security-tracker.debian.org/tracker/CVE-2019-19816) seems to be fixed.

The other one is [this](https://security-tracker.debian.org/tracker/CVE-2019-19814).

**Comment by wglambert** [comment]
https://security-tracker.debian.org/tracker/CVE-2019-19816
Related to the Linux kernel so not image-related. And it's unfixed in Buster anyway (if the host were using Buster)

https://security-tracker.debian.org/tracker/CVE-2019-19814
Linux kernel issue again, and also unfixed in Buster
