### ISSUE TITLE
Problems pulling java:8

### ISSUE THREAD

**Issue by jonasjeeliasson** [docker-library/openjdk#42]
Hi,

We have problems pulling the java:8 image right now:

```
$ sudo docker pull java:8
Pulling repository java
99631e385332: Pulling dependent layers
61b3964dfa70: Download complete
f5224fc54ad2: Download complete
25963d635584: Download complete
99631e385332: Error pulling image (8) from java, HTTP code 400
c93122bbb9c8: Download complete
1e57a1c80d7d: Download complete
7795622a29e5: Download complete
609b19fefa6f: Download complete
777d96c72ad9: Download complete
e32c0434d5dc: Download complete
83ebf7b4bc9d: Error pulling dependent layers
FATA[0023] Error pulling image (8) from java, HTTP code 400
```

Appreciate any help!

Br,
Jonas

**Comment by erikthorselius** [comment]
:+1:

**Comment by andrew-cunliffe** [comment]
:+1: 

Same issues we are using AWS Elastic Beanstalk Docker has been working fine till trying to deploy an updated codebase this morning, no changes to how the Docker runs or communicates.

**Comment by kizbitz** [comment]
Working for me on a fresh AWS Ubuntu image:

```
ubuntu@ubuntu:~$ sudo docker pull java:8
8: Pulling from java
61b3964dfa70: Pull complete
f5224fc54ad2: Pull complete
25963d635584: Pull complete
1f7b395e1580: Pull complete
c93122bbb9c8: Pull complete
1e57a1c80d7d: Pull complete
7795622a29e5: Pull complete
609b19fefa6f: Pull complete
777d96c72ad9: Pull complete
e32c0434d5dc: Pull complete
83ebf7b4bc9d: Pull complete
99631e385332: Already exists
java:8: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:870031daaee51cee0120ed8e6c8844a4f1771a051066a0fb916ec7dac11f1942
Status: Downloaded newer image for java:8
ubuntu@ubuntu:~$ date
Mon Jun 15 12:51:55 UTC 2015
```

**Comment by houghvw** [comment]
Hi,

I get this when trying to deploy to AWS Elastic Beanstalk

Failed to pull Docker image java:8: egistry-1.docker.io/v1/, HTTP code 400 99631e385332: Error pulling image (8) from java, HTTP code 400 time="2015-06-15T13:20:13Z" level="fatal" msg="Error pulling image (8) from java, HTTP code 400" . Check snapshot logs for details.

**Comment by andrew-cunliffe** [comment]
OK, I have spent a little time on this since my last message.

It appears (for my case anyhow) that this might be tied to the version of Docker that Elastic Beanstalk was using, the configuration I had was using:

`64bit Amazon Linux 2014.09 v1.2.1 running Docker 1.5.0`

I have just stood up a replacement ELB instance and selected the latest versions

`64bit Amazon Linux 2015.03 v1.4.1 running Docker 1.6.0`

Using this version it manages to pull down the java:8 package.

`2015-06-15 14:13:10 UTC+0100	INFO	Successfully pulled java:8`

However this brings a new problem as for some reason we cannot start the server correctly using the latest versions offered on ELB.

So it appears that perhaps there is no issue with the Docker Repository but more the latest version of the package or changes to Docker itself are the root cause, I shall continue to dig for as long as I can.

**But if you are having problems on Elastic Beanstalk try either creating a new instance or using the 'Rebuild Environment' option.**

**Comment by cpuguy83** [comment]
ping @dmcgowan @stevvooe @dmp42

**Comment by dmp42** [comment]
@cpuguy83 this is a Hub issue.
You should report this on https://support.docker.com

I wish I could do more...

**Comment by rphutchinson** [comment]
:+1: same issue here

**Comment by cpuguy83** [comment]
This issue should be resolved now.
Please test!

**Comment by jonasjeeliasson** [comment]
Hi,

Yeah, it works now :) 

Can I ask what the cause was, so that I can get a better understanding where the problem lies? Is there some smart way you can protect yourself from these kind of problems? We were a bit lucky that the java:8-jre image worked instead. We redeployed the whole stack using that image instead, otherwise we would have been completely down until we found another java 8 docker image to use.

Kind regards,
Jonas

**Comment by cpuguy83** [comment]
No idea, but I'm sure it stems from syncing the c2 registry with the v1 registry.

**Comment by cpuguy83** [comment]
This one can be closed.
