### ISSUE TITLE
Because in the Linux specification for setting environment variables, "." is not allowed

### ISSUE THREAD

**Issue by bwcxyk** [docker-library/openjdk#441]
Because in the Linux specification for setting environment variables, "." is not allowed.
Docker environment variables will not take effect.

**Comment by wglambert** [comment]
I don't think there's anything actionable we could do with the image to remedy this

https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Definitions
>name
>A word consisting solely of letters, numbers, and underscores, and beginning with a letter or underscore. Names are used as shell variable and function names. Also referred to as an identifier.

A period (`.`) doesn't isn't a valid name in Bash

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by tianon** [comment]
Duplicate of https://github.com/docker-library/openjdk/issues/135
