### ISSUE TITLE
No linux/amd64 image available for Openjdk 11 oracle linux yet

### ISSUE THREAD

**Issue by nagasitaramthigulla** [docker-library/openjdk#448]
I see oracle linux jdk 11 images are created but amd64 based images are not available yet
![image](https://user-images.githubusercontent.com/28944608/104294796-a6589800-54e5-11eb-8484-9c004bd6b80e.png)

**Comment by tianon** [comment]
The overall official images build queue was a bit large yesterday / last night due to the merge of a Debian base image update, so you just happened to check before it was up -- it appears to be up now.

See https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what for details on the full lifecycle/process these images go through to be built.
