### ISSUE TITLE
Missing apt sources?

### ISSUE THREAD

**Issue by mohamnag** [docker-library/openjdk#47]
I am trying to setup an android build environment based on java 7 image as described on https://source.android.com/source/initializing.html. but at the very beginning I get a package not found:

```
$  apt-get update && apt-get install bison g++-multilib git gperf libxml2-utils make python-networkx zlib1g-dev:i386 zip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package zlib1g-dev
```

I always assumed that base image is ubuntu, also the content of `/proc/version` says that base is ubuntu but content of `/etc/apt/sources.list` is only:

```
deb http://httpredir.debian.org/debian jessie main
deb http://httpredir.debian.org/debian jessie-updates main
deb http://security.debian.org jessie/updates main
```

so is this intentional not to have ubuntu sources? if so is there a way of installing `zlib1g-dev` on this image?

**Comment by tianon** [comment]
The problem is that you're trying to install the 32bit version of `zlib1g-dev` without 32bit sources.

Do a `dpkg --add-architecture i386` and then try your `apt-get update && ...` again and it should work.

**Comment by mohamnag** [comment]
@tianon I did try that one too and it did not fix the problem, however I managed to fix problem by adding ubuntu's sources into sources file. not sure if that the correct way but it fixed my problem.

**Comment by chenrui333** [comment]
@mohamnag I think you did right, the source repo list should be updated when needed.

**Comment by tianon** [comment]
Doh, right, re-reading I realize you were asking about `deb-src` entries.  You are correct that they're not necessary for the way most folks use the `debian` and `ubuntu` base images, so they're not included by default (since they'll just slow down `apt-get update` runs for most folks), and should be added manually if they're necessary.  I usually like a one-liner like `RUN find /etc/apt/sources.list* -type f -exec sed -i 'p; s/^deb /deb-src /' '{}' +` for this purpose (to make sure I catch them all).  If this somehow creates duplicate `deb-src` entries, the result is harmless since `apt-get` will ignore the dupes. :+1:
