### ISSUE TITLE
open JDK 

### ISSUE THREAD

**Issue by SralexeyOvalniy** [docker-library/openjdk#483]
Hello, I am applied mathematics student in Ukraine, and I read a lot about your idk and code analysis, so would like to try if it is possible

**Comment by wglambert** [comment]
Sure it's hosted over on the Dockerhub with information on how to use it https://hub.docker.com/_/openjdk

If you have further questions you could try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
