### ISSUE TITLE
Adoptopejdk to Adoptium - Eclipse Temurin

### ISSUE THREAD

**Issue by opengeekv2** [docker-library/openjdk#485]
As it is not clear who long adoptopenjdk will keep beingonline do you plan to migrate to Adoptium as your binary source and make this image based on Eclipse Temurin JDK instead?

**Comment by tianon** [comment]
To be clear - this image is not and has never been "based on" AdoptOpenJDK.  Some of the builds it is using (specifically for OpenJDK 8 and 11) are vanilla OpenJDK builds created by Red Hat (under the direction of the relevant updates project lead), and they are generously _hosted_ by the AdoptOpenJDK project:

https://github.com/docker-library/openjdk/blob/198895da839835656064d35ed7b480bfa4587f91/11/jdk/buster/Dockerfile#L33-L45

You can find the tooling responsible for creating them at https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries and https://github.com/AdoptOpenJDK/openjdk8-upstream-binaries.

You can also see in https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/issues/23 where I asked the maintainers what the future home of them might be given the status of the AdoptOpenJDK project and was told that they will continue to be hosted under AdoptOpenJDK.

The builds for other versions (17, 18, 19) are vanilla OpenJDK builds provided by Oracle at https://jdk.java.net/.

**Comment by opengeekv2** [comment]
So, in case of vanilla OpenJDK versions (17 LTS, 18 and 19) they will only be receiving updates for 6 months since release date because that's Oracle's policy for those builds. Am I right? So  6 months from release any tag of this image (even LTSs) will not receive more updates (because of JDK, maybe yes for other layers) since no binaries will be published by Oracle. Is this a correct reasoning? I just want to confirm this so I can make my mind up of what image would I want to use as base.

**Comment by tianon** [comment]
Unfortunately, yes, that is correct for versions 17, 18, and 19 (but as far
as I know, the 8 and 11 builds will be maintained as long as the relevant
updates projects are still maintained).

**Comment by tianon** [comment]
I'd suggest giving https://github.com/docker-library/openjdk/issues/320 a read through to understand the flame war we endured that led us to the current situation -- unfortunately, we can't/won't be promoting any particular distribution as "OpenJDK" here (which is why we stick to the strictly vanilla builds, even though the situation is far from ideal).

I would love to see this documented better in the image description, but it's a bit complicated and we definitely can't give any specific recommendations -- perhaps a middle ground would be to list _all_ the distributions available in the official images program in alphabetical order or something?  The tricky part is coming up with some good neutral wording to describe the current situation and what it means for users.

**Comment by opengeekv2** [comment]
I'm sorry if I picked a sensitive issue in the comunity. Also I reopened It
by accident.

El dv., 14 de gen. 2022, 19:14, Tianon Gravi ***@***.***> va
escriure:
