### ISSUE TITLE
java:latest missing JavaFx

### ISSUE THREAD

**Issue by dannypurcell** [docker-library/openjdk#53]
I have an app referencing `javafx.util.Pair` from the JavaFx library. Trying to run with an image built from `java:latest` gives `java.lang.ClassNotFoundException: javafx.util.Pair`.

JavaFX is on the default class-path for the Oracle runtime so it's reasonable to assume Java developers switching to docker may be using classes from that library.

Can we set up some tags that are fully compatible with the Oracle releases?

**Comment by yosifkit** [comment]
Because of Oracle's licensing, we are unable to package Oracle Java: https://github.com/docker-library/docs/blob/master/java/README.md#why-is-this-only-openjdkopenjre.  If you know of an official way to make the OpenJDK work, we could probably add that.

**Comment by md5** [comment]
If you're looking to get unblocked, you can install the `openjfx` Debian package. It adds about 70 mb to the image, so I don't think it makes a lot of sense to add it by default.

I'm also curious what sort of software you're running in a container that requires JavaFX since it's meant for desktop applications.

**Comment by md5** [comment]
Also, the `openjfx` package will only work with the `java:8-*` images. My understanding is that OpenJDK 9 will come with OpenJFX integrated, though I don't know how this will affect the Debian packaging.

**Comment by dannypurcell** [comment]
This is not a graphical app but merely references classes from the JavaFx package.

This is not a request for an Oracle distribution but rather an open jdk distribution whose default class path matches that of the Oracle distribution. 

This would help developers who have been building against Oracle on RedHat try out Docker builds without first having to smash their heads against the wall for while.

@md5 Thanks for the alternatives.
If the JavaFx package is not part of any specification then I think the size argument holds. However, Oracle does advertise JavaFx as being part of Java 8 so I'm thinking it's just preferences of the Linux distributors at play here.

**Comment by tianon** [comment]
I think http://openjdk.java.net/projects/openjfx/ is probably the best place for information about JavaFX with OpenJDK.

As an extra point of interest, we have officially renamed this image from `java` to `openjdk` (https://github.com/docker-library/official-images/pull/2046, https://github.com/docker-library/docs/pull/660), which I think helps further clear up expectations regarding things "Java" is supposed to or expected to include (since this image contains OpenJDK, which is "the open-source reference implementation of Java", but is not necessarily what most folks are thinking of when they ask for "Java").

IMO it's also worth pointing out that Debian does have an `openjfx` package (https://packages.debian.org/jessie-backports/openjfx), but it appears to be focused on OpenJDK 8 specificially.

Thanks!

**Comment by pulkitsinghal** [comment]
Its only fair to point out that after scouring the web, it is possible to build a docker image with JavaFX easily as outlined in this tutorial: https://dexvis.wordpress.com/2016/04/04/running-javafx-in-a-docker-container/

**Comment by greyshine** [comment]
As "pulkitsinghal" mentioned. the dexvis's blog post did not help me setting up javafx. I end up having problems running the docker build.

**Comment by pulkitsinghal** [comment]
@greyshine what problems did you have?

I needed to run a JIRA client inside docker which required java and javafx ... and I was able to use that blog to do what i needed.

Here’s the dockerfile that worked for me:

https://github.com/pulkitsinghal/jira-client-inside-docker/blob/master/Dockerfile

**Comment by pulkitsinghal** [comment]
Also when I search using google or inside dockerhub, several images claiming to have javafx Oreo stalked pop up. Have you tried any of those?

**Comment by koppor** [comment]
https://github.com/docker-library/openjdk/issues/158 describes how to build the image for oneself
