### ISSUE TITLE
Script to make it easier setting Xmx values

### ISSUE THREAD

**Issue by carlossg** [docker-library/openjdk#59]
We have this script in the `jenkins` image to set better default Xmx values according to the docker memory limits from `/sys/fs/cgroup/memory/memory.limit_in_bytes`
It would be useful to add it to the base `java` image
https://github.com/jenkinsci/docker/pull/182/files

If Xmx is not set the JVM will use by default 1/4th (in most cases) of the host memory
This can cause the Kernel to kill the container if the JVM memory grows over the cgroups limit
because the JVM is not aware of that limit and doesn't invoke the GC
Setting it by default to 0.5 times the memory limited by cgroups, customizable with `JVM_HEAP_RATIO`

I can submit a PR if it seems reasonable.

**Comment by yosifkit** [comment]
It seems somewhat reasonable to me, though I am not a java user so I could be wrong.  A problem I see is when the user doesn't set `-m` on their docker run and so the script sets the java limit to 1/2 of the largest 64-bit integer or about 4 Exabytes (at least on my machine, since the value of `/sys/fs/cgroup/memory/memory.limit_in_bytes` is probably machine dependent).

**Comment by carlossg** [comment]
good point, I have considered that case now, using the host memory available if memory is not limited

**Comment by carlossg** [comment]
PR sent as #71
