### ISSUE TITLE
Why so many tags for each version?

### ISSUE THREAD

**Issue by saljuama** [docker-library/openjdk#67]
I'm sure there is a reason for it, and I fail to see it, but I'm still wondering, why are there so many tags for the same base image? For example, with the version 8 jdk, there are the following tags: `8`, `8-jdk`, `jdk`, `openjdk-8`, `openjdk-8-jdk`, and of course `latest`, but this last one i understand.

This leads to different images using these different tags, and probably shouldn't be a problem, as they all share the same hash, but, because of this, I've noticed that in my local images, I ended up having different versions of the same java image, which turns into not all the running containers using the same version.

Of course this can be easily solved by pulling all the tags and keeping all of them up to date, but sometimes becomes a bit annoying.

**Comment by tianon** [comment]
This was partially due to an initial misguided thought that we'd have multiple implementations of "Java" under the single image name `java`.  With https://github.com/docker-library/docs/pull/660, the image has officially been renamed to be `openjdk` (and the `java` image is now deprecated), and thus all the `openjdk-` tags are gone.

As for why we have `8-jdk`, `jdk`, `jre`, etc, that's so that users can apply the amount of specificity that they care about.  For example, some users just want "some JRE", and don't really care which version (`openjdk:jre`).  Some users want "the latest 8-series JDK" (`openjdk:8-jre`).  Some may want specifically 7u111 JRE, hence `openjdk:7u111-jre`.
