### ISSUE TITLE
timezone not correctly picked up from host system

### ISSUE THREAD

**Issue by thaitzer** [docker-library/openjdk#80]
Hi!
I have an issue with the timezone in the java:8 image.

I have successfully configured the container time-zone to be the same as the host time-zone by adding the following to docker-compose
` volumes:
- /etc/localtime:/etc/localtime:ro`
  However, the JVM is still running in the default time-zone (UTC) and not picking up on the system timezone.

I have also thought that maybe the JVM does not find the zone info so I also added a volume for that:
`- /usr/share/zoneinfo/:/usr/share/zoneinfo/:ro`
However that was not successful.

I am not sure if this really is a bug or if I am doing something wrong ...

Thank you in advance,
Thomas

**Comment by tianon** [comment]
Using the following source file, I'm able to successfully change Java's timezone via the `TZ` environment variable:

```java
import java.time.ZonedDateTime;

public class Main {
	public static void main(String[] args) {
		ZonedDateTime now = ZonedDateTime.now();
		System.out.println(now);
	}
}
```

```console
$ docker run -it --rm -v "$PWD/Main.java":/tmp/Main.java:ro -w /tmp openjdk:8-jdk bash -c 'javac Main.java && java Main'
2018-01-03T21:40:25.145Z[Etc/UTC]
$ docker run -e TZ='America/Denver' -it --rm -v "$PWD/Main.java":/tmp/Main.java:ro -w /tmp openjdk:8-jdk bash -c 'javac Main.java && java Main'
2018-01-03T14:40:44.219-07:00[America/Denver]
```

However, I was not able to get `/etc/localtime` to work, so I guess Java doesn't support it:
```console
$ docker run -v /etc/localtime:/etc/localtime:ro -it --rm -v "$PWD/Main.java":/tmp/Main.java:ro -w /tmp openjdk:8-jdk bash -c 'javac Main.java && java Main'
2018-01-03T21:40:58.901Z[Etc/UTC]
$ docker run -v "$(readlink -f /etc/localtime)":/etc/localtime:ro -it --rm -v "$PWD/Main.java":/tmp/Main.java:ro -w /tmp openjdk:8-jdk bash -c 'javac Main.java && java Main'
2018-01-03T21:42:08.896Z[Etc/UTC]
```

https://stackoverflow.com/a/6496/433558 seems to suggest that it's a quirk of how Java determines the local timezone (http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6456628).

Closing since there's nothing we can really do here.
