### ISSUE TITLE
8-jre-alpine CMD `java` not found

### ISSUE THREAD

**Issue by artheus** [docker-library/openjdk#94]
There seems to be a problem with the alpine images. At least there is for me.
I also tried the deprecated java:8-jre-alpine image and got the same result.

Dockerfile:
```Dockerfile
FROM openjdk:8-jre-alpine
ARG FINALNAME
ADD /$FINALNAME /$FINALNAME
CMD ["java", "-jar", $FINALNAME]
```
(Do not worry about the `FINALNAME` argument, that works as it should, my problem is the `CMD` line)

Run command:
```
artheus# docker run -it 106738dc2d2e
/bin/sh: [java,: not found
```

I have tried it with both docker 1.12 and 1.13.

I've tried running a container from my image specifying the command myself.
```
artheus# docker run -it 106738dc2d2e java -jre my-application-0.0.1-SNAPSHOT.jar
*** Runs perfectly ***
```

**Comment by artheus** [comment]
I also tried cleaning out the cache of images and containers on my machines completely, but the issue still persists.

**Comment by tianon** [comment]
The problem is your `$FINALNAME` argument -- `["java", "-jar", $FINALNAME]` is not valid JSON, so it's passed to the shell as-is, and that's why your error message references `[java,` as the command that's not found (it's being passed to the shell).  If you must have that final argument come from an environment variable, you'll have to switch to the shell syntax, although using `exec` can ensure that `java` still ends up being the only thing running:
```dockerfile
CMD exec java -jar "$FINALNAME"
```

**Comment by bascom241** [comment]
Just seeing this issue and trust me if you run the same command on git bash it works hundred. Now the question is why??
